spring:
  batch:
    job:
      #job name ????? job? ?? ??? ?? ??? ??????.
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_batch
      username: ssafy
      password: ssafy
      driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      data-locations: classpath:person.sql
batch:
  initialize-schema: never